// Swedish Forces Pack Arsenal Preset

// Mods needed:
// SFP

GRLIB_arsenal_weapons = [
	"sfp_ag90",
	"sfp_ag90_base",
	"sfp_ak4b",
	"sfp_ak4c",
	"sfp_ak4d",
	"sfp_ak5c",
	"sfp_ak5c_alt",
	"sfp_ak5c_alt_plastic",
	"sfp_ak5c_plastic",
	"sfp_ak5c_m203",
	"sfp_ak5c_m203_plastic",
	"sfp_ak5dmk2",
	"sfp_ak5dmk2_plastic",
	"sfp_grg86",
	"sfp_ksp58B2",
	"sfp_ksp58c",
	"sfp_ksp90c",
	"sfp_psg90",
	"sfp_psg90_base",
	"sfp_pskott86",
	"sfp_rb57",
	"sfp_p88",
	"sfp_p226"
];

GRLIB_arsenal_magazines = [
	"1Rnd_HE_Grenade_shell",
	"ClaymoreDirectionalMine_Remote_Mag",
	"SatchelCharge_Remote_Mag",
	"sfp_9Rnd_762x51_psg90",
	"sfp_9Rnd_762x51_psg90_prick",
	"sfp_10Rnd_127x99_ag90",
	"sfp_15Rnd_9x19_Mag",
	"sfp_17Rnd_9x19_Mag",
	"sfp_20Rnd_762x51_ak4",
	"sfp_30Rnd_556x45_Stanag",
	"sfp_30Rnd_556x45_Stanag_plastic",
	"sfp_30Rnd_556x45_Stanag_tracer",
	"sfp_30Rnd_556x45_Stanag_tracer_plastic",
	"sfp_50Rnd_762x51_ksp58",
	"sfp_100Rnd_762x51_ksp58",
	"sfp_200Rnd_556x45_ksp90",
	"sfp_grg_he_mag",
	"sfp_grg_heat_62_mag",
	"sfp_grg_heat_66_mag",
	"sfp_grg_heat_mag",
	"sfp_grg_illum_mag",
	"sfp_grg_smoke_mag",
	"sfp_handgrenade_shgr56",
	"sfp_handgrenade_shgr2000",
	"sfp_handgrenade_shgr07",
	"sfp_pskott86_mag",
	"sfp_rb57_mag",
	"sfp_sprdeg46_mag",
	"sfp_strvm5_mag",
	"SmokeShell"
];

GRLIB_arsenal_items = [
	"B_UavTerminal",
	"Binocular",
	"ItemCompass",
	"ItemGPS",
	"ItemMap",
	"ItemWatch",
	"Laserdesignator",
	"FirstAidKit",
	"Medikit",
	"MineDetector",
	"NVGoggles",
	"NVGoggles_INDEP",
	"NVGoggles_OPFOR",
	"Rangefinder",
	"ToolKit",
	"tf_anprc152",
	"TFAR_anprc152",
	"H_HelmetCrew_I",
	"sfp_dbal2",
	"sfp_tlr2",
	"sfp_m87_flying_suit",
	"sfp_flighthelmet116",
	"sfp_m90w_uniform",
	"sfp_m90w_uniform_dirty",
	"sfp_m90w_uniform_tshirt",
	"sfp_ghillie_uniform",
	"sfp_optic_3x_aimpoint",
	"sfp_optic_aimpoint",
	"sfp_optic_aimpoint_t1",
	"sfp_optic_aimpoint_twist",
	"sfp_optic_kikarsikte90b_10x",
	"sfp_stridsvast08",
	"sfp_kroppsskydd12",
	"sfp_kroppsskydd12_crew",
	"sfp_kroppsskydd12_tl",
	"sfp_kroppsskydd12_at",
	"sfp_kroppsskydd12_medic",
	"sfp_kroppsskydd12_holster",
	"sfp_headset",
	"sfp_peltor",
	"sfp_m90w_cap",
	"sfp_m90w_cap_peltor",
	"sfp_m90w_helmet",
	"sfp_m90w_helmet_headset",
	"sfp_m90w_helmet_headset_nvg",
	"sfp_m90w_helmet_peltor",
	"sfp_m90w_helmet_nvg",
	"sfp_m90w_helmet_peltor_nvg"
];

GRLIB_arsenal_backpacks = [
	"sfp_backpack_grg_loader",
	"sfp_backpack_lk35",
	"sfp_backpack_sjvv9",
	"sfp_backpack_stridssack08",
	"sfp_backpack_stridssack2000",
	"sfp_ra180",
	"sfp_stridssack2000_ra_ksk12"
];
